<template>
  <div class="Hero">
    <div class="Hero__top">
      <p class="Hero__top--txt">Legal Notices</p>
      <logotypeSVG class="Hero__top--logo" />
      <p class="Hero__top--subtext">When art meets other intelligences</p>
      <AnimatedGradient class="Hero__top--gradient" />
    </div>
  </div>

  <article class="section">
    <h2 class="section__title">Legal Notices</h2>

    <div class="about">
      <h3 class="about__title">Publisher Information</h3>
      <ul class="about__text">
        <li>
          <p><strong>Website Publisher: </strong>Echoes Of Elsewhere</p>
        </li>
        <li>
          <p><strong>Address: </strong>4 Place Tharradin, 25200 Montbéliard</p>
        </li>
        <li>
          <p><strong>Contact: </strong>contact@echoesofelsewhere@gmail.com</p>
        </li>
        <li>
          <p>
            <strong>Publication Director: </strong>Lilian Chesneau Ciccarelli
          </p>
        </li>
        <li>
          <p><strong>Website Host: </strong>Vercel</p>
        </li>
      </ul>

      <h3 class="about__title">Intellectual Property</h3>
      <p class="about__text">
        The content on this website, including but not limited to textual
        materials, images, and audio-visual works, encompasses both
        human-created and AI-generated creations. For AI-generated content,
        Echoes Of Elsewhere utilizes various AI tools and platforms, each
        governed by its own set of terms and conditions regarding the use and
        distribution of generated content.
      </p>
      <p class="about__text">
        It is our policy to respect the intellectual property rights of others,
        including works created by artificial intelligence where such rights are
        recognized. Where AI-generated content is used, we ensure that such use
        is in accordance with the licensing agreements of the AI platforms
        employed, and we acknowledge any rights or attributions as required by
        these platforms.
      </p>
      <p class="about__text">
        For inquiries or permissions related to the use of any content from this
        site, including AI-generated works, please contact the publisher.
      </p>

      <h3 class="about__title">Cookies Policy</h3>
      <p class="about__text">
        This website does not use cookies to track user activity or personal
        information.
      </p>

      <h3 class="about__title">Liability</h3>
      <p class="about__text">
        Echoes Of Elsewhere cannot be held responsible for any direct or
        indirect damage caused to the user's equipment when accessing the
        website. Furthermore, Echoes Of Elsewhere disclaims liability for any
        subsequent changes to the content generated by AI tools.
      </p>

      <h3 class="about__title">External Links</h3>
      <p class="about__text">
        This website may contain links to other sites. Echoes Of Elsewhere has
        no control over these external sites and is not responsible for their
        content.
      </p>

      <h3 class="about__title">Modifications to Legal Notices</h3>
      <p class="about__text">
        Echoes Of Elsewhere reserves the right to modify or update these legal
        notices at any time without notice. Users are encouraged to regularly
        consult this page to stay informed of any changes.
      </p>

      <h3 class="about__title">Governing Law</h3>
      <p class="about__text">
        This website and its legal notices are governed by French law. Any
        disputes related to the use of this website will be subject to the
        exclusive jurisdiction of the French courts. In the event of a dispute,
        efforts will be made to seek an amicable solution before any legal
        action is taken. Should legal proceedings become necessary, they will be
        brought before the competent courts within the jurisdiction of France.
      </p>
    </div>
  </article>
</template>

<style lang="scss" scoped>
.Hero {
  margin-top: rem(150);

  &__top {
    position: relative;

    &--gradient {
      position: absolute;
      top: rem(-100);
      z-index: -1;
    }

    &--logo {
      margin: rem(50) rem(20) rem(15) rem(20);
    }

    &--subtext {
      border-bottom: solid 1px $Dark-Purple;
      padding-bottom: rem(50);
      font-size: $font-size-small;
      text-align: center;
    }

    &--txt {
      border-bottom: solid 1px $Dark-Purple;
      border-top: solid 1px $Dark-Purple;
      padding: rem(15) 0;
      text-align: center;
      text-transform: uppercase;
    }
  }
}

.section {
  margin: rem(100) 0 rem(200) 0;

  &__title {
    color: $English-Violet;
    margin: 0 rem(20) rem(50) rem(20);

    font-family: $font-display;
    font-size: $font-size-gianter;
    text-transform: uppercase;
  }
}

.about {
  margin: 0 rem(20) 0 rem(20);

  &__title {
    font-weight: 600;
    margin-bottom: rem(20);
    text-decoration: underline;
  }

  &__text {
    margin-bottom: rem(50);
  }
}
</style>
